/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.100
 * Generated at: 2025-05-28 10:01:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1747448159602L));
    _jspx_dependants.put("jar:file:/home/d4ante/Desktop/java-Hotelmanagment/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/HotelWebApp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425958870000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>Luxury Hotel Management System</title>\n");
      out.write("    <!-- Font Awesome for icons -->\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css\">\n");
      out.write("    <!-- Embedded CSS - No external file needed -->\n");
      out.write("    <style>\n");
      out.write("        /* Import Google Fonts */\n");
      out.write("        @import url('https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&family=Playfair+Display:wght@400;700&display=swap');\n");
      out.write("\n");
      out.write("        /* CSS Variables for consistent theming */\n");
      out.write("        :root {\n");
      out.write("          --primary-color: #1e3a8a;\n");
      out.write("          --secondary-color: #3b82f6;\n");
      out.write("          --accent-color: #f59e0b;\n");
      out.write("          --light-color: #f3f4f6;\n");
      out.write("          --dark-color: #1f2937;\n");
      out.write("          --success-color: #10b981;\n");
      out.write("          --danger-color: #ef4444;\n");
      out.write("          --warning-color: #f59e0b;\n");
      out.write("          --info-color: #3b82f6;\n");
      out.write("          --box-shadow: 0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05);\n");
      out.write("          --transition: all 0.3s ease;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Reset and Base Styles */\n");
      out.write("        * {\n");
      out.write("          margin: 0;\n");
      out.write("          padding: 0;\n");
      out.write("          box-sizing: border-box;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        body {\n");
      out.write("          font-family: 'Poppins', sans-serif;\n");
      out.write("          line-height: 1.6;\n");
      out.write("          color: var(--dark-color);\n");
      out.write("          background-color: #f9fafb;\n");
      out.write("          background-image: linear-gradient(135deg, #f5f7fa 0%, #c3cfe2 100%);\n");
      out.write("          background-attachment: fixed;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .container {\n");
      out.write("          width: 90%;\n");
      out.write("          max-width: 1200px;\n");
      out.write("          margin: 0 auto;\n");
      out.write("          padding: 0;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Enhanced Header Styles */\n");
      out.write("        header {\n");
      out.write("          background: linear-gradient(to right, var(--primary-color), var(--secondary-color));\n");
      out.write("          color: white;\n");
      out.write("          padding: 1.5rem 0;\n");
      out.write("          box-shadow: var(--box-shadow);\n");
      out.write("          position: relative;\n");
      out.write("          z-index: 10;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        header::before {\n");
      out.write("          content: '';\n");
      out.write("          position: absolute;\n");
      out.write("          bottom: -10px;\n");
      out.write("          left: 0;\n");
      out.write("          right: 0;\n");
      out.write("          height: 10px;\n");
      out.write("          background: linear-gradient(45deg, transparent 33.33%, var(--light-color) 33.33%, var(--light-color) 66.66%, transparent 66.66%);\n");
      out.write("          background-size: 20px 20px;\n");
      out.write("          z-index: 5;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        header h1 {\n");
      out.write("          font-family: 'Playfair Display', serif;\n");
      out.write("          text-align: center;\n");
      out.write("          margin: 0;\n");
      out.write("          font-size: 2.5rem;\n");
      out.write("          font-weight: 700;\n");
      out.write("          text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.2);\n");
      out.write("          letter-spacing: 1px;\n");
      out.write("          padding-bottom: 0.5rem;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Modern Navigation */\n");
      out.write("        header nav {\n");
      out.write("          text-align: center;\n");
      out.write("          padding-top: 1rem;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        header nav ul {\n");
      out.write("          padding: 0;\n");
      out.write("          list-style: none;\n");
      out.write("          display: flex;\n");
      out.write("          justify-content: center;\n");
      out.write("          flex-wrap: wrap;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        header nav ul li {\n");
      out.write("          margin: 0 5px;\n");
      out.write("          position: relative;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        header nav a {\n");
      out.write("          color: white;\n");
      out.write("          text-decoration: none;\n");
      out.write("          text-transform: uppercase;\n");
      out.write("          font-size: 0.9rem;\n");
      out.write("          font-weight: 500;\n");
      out.write("          letter-spacing: 1px;\n");
      out.write("          padding: 10px 15px;\n");
      out.write("          border-radius: 4px;\n");
      out.write("          transition: var(--transition);\n");
      out.write("          display: inline-block;\n");
      out.write("          position: relative;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        header nav a::after {\n");
      out.write("          content: '';\n");
      out.write("          position: absolute;\n");
      out.write("          width: 0;\n");
      out.write("          height: 2px;\n");
      out.write("          bottom: 0;\n");
      out.write("          left: 50%;\n");
      out.write("          background-color: white;\n");
      out.write("          transition: var(--transition);\n");
      out.write("          transform: translateX(-50%);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        header nav a:hover {\n");
      out.write("          color: var(--accent-color);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        header nav a:hover::after {\n");
      out.write("          width: 80%;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        header nav a.active {\n");
      out.write("          background-color: rgba(255, 255, 255, 0.2);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Enhanced Main Content Styles */\n");
      out.write("        main {\n");
      out.write("          background: white;\n");
      out.write("          border-radius: 10px;\n");
      out.write("          margin: 2rem 0;\n");
      out.write("          padding: 2rem;\n");
      out.write("          box-shadow: var(--box-shadow);\n");
      out.write("          position: relative;\n");
      out.write("          overflow: hidden;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        main::before {\n");
      out.write("          content: '';\n");
      out.write("          position: absolute;\n");
      out.write("          top: 0;\n");
      out.write("          left: 0;\n");
      out.write("          width: 100%;\n");
      out.write("          height: 5px;\n");
      out.write("          background: linear-gradient(to right, var(--primary-color), var(--secondary-color), var(--accent-color));\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        main h2 {\n");
      out.write("          font-family: 'Playfair Display', serif;\n");
      out.write("          color: var(--primary-color);\n");
      out.write("          text-align: center;\n");
      out.write("          margin-bottom: 1.5rem;\n");
      out.write("          font-size: 2rem;\n");
      out.write("          position: relative;\n");
      out.write("          padding-bottom: 10px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        main h2::after {\n");
      out.write("          content: '';\n");
      out.write("          position: absolute;\n");
      out.write("          bottom: 0;\n");
      out.write("          left: 50%;\n");
      out.write("          transform: translateX(-50%);\n");
      out.write("          width: 80px;\n");
      out.write("          height: 3px;\n");
      out.write("          background: var(--accent-color);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Enhanced Footer */\n");
      out.write("        footer {\n");
      out.write("          text-align: center;\n");
      out.write("          padding: 1.5rem 0;\n");
      out.write("          background: var(--dark-color);\n");
      out.write("          color: white;\n");
      out.write("          margin-top: 2rem;\n");
      out.write("          border-radius: 10px 10px 0 0;\n");
      out.write("          position: relative;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        footer p {\n");
      out.write("          margin: 0;\n");
      out.write("          font-size: 0.9rem;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Home Page Specific Styles */\n");
      out.write("        .welcome-section {\n");
      out.write("          text-align: center;\n");
      out.write("          padding: 2rem 0;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .welcome-message {\n");
      out.write("          font-size: 1.2rem;\n");
      out.write("          color: var(--dark-color);\n");
      out.write("          max-width: 800px;\n");
      out.write("          margin: 0 auto 2rem;\n");
      out.write("          line-height: 1.8;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .features-grid {\n");
      out.write("          display: grid;\n");
      out.write("          grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));\n");
      out.write("          gap: 2rem;\n");
      out.write("          margin: 3rem 0;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .feature-card {\n");
      out.write("          background: white;\n");
      out.write("          border-radius: 8px;\n");
      out.write("          padding: 1.5rem;\n");
      out.write("          box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);\n");
      out.write("          transition: var(--transition);\n");
      out.write("          text-align: center;\n");
      out.write("          border: 1px solid #eee;\n");
      out.write("          position: relative;\n");
      out.write("          overflow: hidden;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .feature-card:hover {\n");
      out.write("          transform: translateY(-5px);\n");
      out.write("          box-shadow: 0 10px 15px rgba(0, 0, 0, 0.1);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .feature-card::before {\n");
      out.write("          content: '';\n");
      out.write("          position: absolute;\n");
      out.write("          top: 0;\n");
      out.write("          left: 0;\n");
      out.write("          width: 100%;\n");
      out.write("          height: 4px;\n");
      out.write("          background: var(--secondary-color);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .feature-card:nth-child(2)::before {\n");
      out.write("          background: var(--accent-color);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .feature-card:nth-child(3)::before {\n");
      out.write("          background: var(--success-color);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .feature-card:nth-child(4)::before {\n");
      out.write("          background: var(--info-color);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .feature-icon {\n");
      out.write("          font-size: 2.5rem;\n");
      out.write("          margin-bottom: 1rem;\n");
      out.write("          color: var(--primary-color);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .feature-card h3 {\n");
      out.write("          margin-bottom: 0.5rem;\n");
      out.write("          color: var(--dark-color);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .feature-card p {\n");
      out.write("          color: #666;\n");
      out.write("          font-size: 0.9rem;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .cta-buttons {\n");
      out.write("          display: flex;\n");
      out.write("          justify-content: center;\n");
      out.write("          gap: 1rem;\n");
      out.write("          margin-top: 2rem;\n");
      out.write("          flex-wrap: wrap;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .btn {\n");
      out.write("          display: inline-block;\n");
      out.write("          padding: 0.8rem 1.5rem;\n");
      out.write("          border-radius: 50px;\n");
      out.write("          text-decoration: none;\n");
      out.write("          font-weight: 500;\n");
      out.write("          text-transform: uppercase;\n");
      out.write("          letter-spacing: 1px;\n");
      out.write("          font-size: 0.9rem;\n");
      out.write("          transition: var(--transition);\n");
      out.write("          cursor: pointer;\n");
      out.write("          border: none;\n");
      out.write("          outline: none;\n");
      out.write("          box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .btn-primary {\n");
      out.write("          background: var(--primary-color);\n");
      out.write("          color: white;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .btn-primary:hover {\n");
      out.write("          background: #152a66;\n");
      out.write("          transform: translateY(-2px);\n");
      out.write("          box-shadow: 0 6px 8px rgba(0, 0, 0, 0.15);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .btn-secondary {\n");
      out.write("          background: var(--accent-color);\n");
      out.write("          color: white;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .btn-secondary:hover {\n");
      out.write("          background: #e08e0b;\n");
      out.write("          transform: translateY(-2px);\n");
      out.write("          box-shadow: 0 6px 8px rgba(0, 0, 0, 0.15);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Hotel Image Showcase */\n");
      out.write("        .hotel-showcase {\n");
      out.write("          margin: 3rem 0;\n");
      out.write("          position: relative;\n");
      out.write("          height: 300px;\n");
      out.write("          border-radius: 10px;\n");
      out.write("          overflow: hidden;\n");
      out.write("          box-shadow: var(--box-shadow);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .showcase-slide {\n");
      out.write("          position: absolute;\n");
      out.write("          top: 0;\n");
      out.write("          left: 0;\n");
      out.write("          width: 100%;\n");
      out.write("          height: 100%;\n");
      out.write("          opacity: 0;\n");
      out.write("          transition: opacity 1s ease-in-out;\n");
      out.write("          background-size: cover;\n");
      out.write("          background-position: center;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .showcase-slide.active {\n");
      out.write("          opacity: 1;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .showcase-slide:nth-child(1) {\n");
      out.write("          background-image: url('https://source.unsplash.com/random/1200x600/?hotel-lobby');\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .showcase-slide:nth-child(2) {\n");
      out.write("          background-image: url('https://source.unsplash.com/random/1200x600/?hotel-room');\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .showcase-slide:nth-child(3) {\n");
      out.write("          background-image: url('https://source.unsplash.com/random/1200x600/?hotel-pool');\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .showcase-caption {\n");
      out.write("          position: absolute;\n");
      out.write("          bottom: 0;\n");
      out.write("          left: 0;\n");
      out.write("          right: 0;\n");
      out.write("          background: rgba(0, 0, 0, 0.6);\n");
      out.write("          color: white;\n");
      out.write("          padding: 1rem;\n");
      out.write("          text-align: center;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Stats Section */\n");
      out.write("        .stats-section {\n");
      out.write("          display: flex;\n");
      out.write("          justify-content: space-around;\n");
      out.write("          flex-wrap: wrap;\n");
      out.write("          margin: 3rem 0;\n");
      out.write("          text-align: center;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .stat-item {\n");
      out.write("          padding: 1rem;\n");
      out.write("          flex: 1;\n");
      out.write("          min-width: 150px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .stat-number {\n");
      out.write("          font-size: 2.5rem;\n");
      out.write("          font-weight: 700;\n");
      out.write("          color: var(--primary-color);\n");
      out.write("          margin-bottom: 0.5rem;\n");
      out.write("          display: block;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .stat-label {\n");
      out.write("          font-size: 0.9rem;\n");
      out.write("          color: #666;\n");
      out.write("          text-transform: uppercase;\n");
      out.write("          letter-spacing: 1px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Testimonials */\n");
      out.write("        .testimonials {\n");
      out.write("          margin: 3rem 0;\n");
      out.write("          position: relative;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .testimonial-container {\n");
      out.write("          overflow: hidden;\n");
      out.write("          position: relative;\n");
      out.write("          padding: 2rem 0;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .testimonial-slide {\n");
      out.write("          text-align: center;\n");
      out.write("          padding: 1.5rem;\n");
      out.write("          background: #f8f9fa;\n");
      out.write("          border-radius: 8px;\n");
      out.write("          margin: 0 auto;\n");
      out.write("          max-width: 800px;\n");
      out.write("          opacity: 0;\n");
      out.write("          position: absolute;\n");
      out.write("          top: 0;\n");
      out.write("          left: 0;\n");
      out.write("          right: 0;\n");
      out.write("          transition: opacity 0.5s ease-in-out;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .testimonial-slide.active {\n");
      out.write("          opacity: 1;\n");
      out.write("          position: relative;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .testimonial-text {\n");
      out.write("          font-style: italic;\n");
      out.write("          margin-bottom: 1rem;\n");
      out.write("          position: relative;\n");
      out.write("          padding: 0 2rem;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .testimonial-text::before,\n");
      out.write("        .testimonial-text::after {\n");
      out.write("          content: '\"';\n");
      out.write("          font-size: 3rem;\n");
      out.write("          color: var(--accent-color);\n");
      out.write("          opacity: 0.3;\n");
      out.write("          position: absolute;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .testimonial-text::before {\n");
      out.write("          top: -20px;\n");
      out.write("          left: 0;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .testimonial-text::after {\n");
      out.write("          bottom: -40px;\n");
      out.write("          right: 0;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .testimonial-author {\n");
      out.write("          font-weight: 600;\n");
      out.write("          color: var(--primary-color);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .testimonial-role {\n");
      out.write("          font-size: 0.8rem;\n");
      out.write("          color: #666;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .testimonial-dots {\n");
      out.write("          display: flex;\n");
      out.write("          justify-content: center;\n");
      out.write("          margin-top: 1rem;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .dot {\n");
      out.write("          width: 10px;\n");
      out.write("          height: 10px;\n");
      out.write("          background: #ccc;\n");
      out.write("          border-radius: 50%;\n");
      out.write("          margin: 0 5px;\n");
      out.write("          cursor: pointer;\n");
      out.write("          transition: var(--transition);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .dot.active {\n");
      out.write("          background: var(--primary-color);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Message Styles */\n");
      out.write("        .message {\n");
      out.write("          padding: 1rem;\n");
      out.write("          margin: 1rem 0;\n");
      out.write("          border-radius: 8px;\n");
      out.write("          text-align: center;\n");
      out.write("          animation: fadeIn 0.5s ease-in-out;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        @keyframes fadeIn {\n");
      out.write("          from { opacity: 0; transform: translateY(-10px); }\n");
      out.write("          to { opacity: 1; transform: translateY(0); }\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .success-message {\n");
      out.write("          background-color: rgba(16, 185, 129, 0.1);\n");
      out.write("          color: var(--success-color);\n");
      out.write("          border: 1px solid rgba(16, 185, 129, 0.2);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .error-message {\n");
      out.write("          background-color: rgba(239, 68, 68, 0.1);\n");
      out.write("          color: var(--danger-color);\n");
      out.write("          border: 1px solid rgba(239, 68, 68, 0.2);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Responsive Design */\n");
      out.write("        @media (max-width: 768px) {\n");
      out.write("          header h1 {\n");
      out.write("            font-size: 1.8rem;\n");
      out.write("          }\n");
      out.write("          \n");
      out.write("          header nav ul {\n");
      out.write("            flex-direction: column;\n");
      out.write("            align-items: center;\n");
      out.write("          }\n");
      out.write("          \n");
      out.write("          header nav ul li {\n");
      out.write("            margin: 5px 0;\n");
      out.write("          }\n");
      out.write("          \n");
      out.write("          .features-grid {\n");
      out.write("            grid-template-columns: 1fr;\n");
      out.write("          }\n");
      out.write("          \n");
      out.write("          .hotel-showcase {\n");
      out.write("            height: 200px;\n");
      out.write("          }\n");
      out.write("          \n");
      out.write("          .cta-buttons {\n");
      out.write("            flex-direction: column;\n");
      out.write("            align-items: center;\n");
      out.write("          }\n");
      out.write("          \n");
      out.write("          .btn {\n");
      out.write("            width: 100%;\n");
      out.write("            max-width: 300px;\n");
      out.write("            margin-bottom: 0.5rem;\n");
      out.write("            text-align: center;\n");
      out.write("          }\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Animation Keyframes */\n");
      out.write("        @keyframes fadeIn {\n");
      out.write("          from { opacity: 0; }\n");
      out.write("          to { opacity: 1; }\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        @keyframes slideInFromLeft {\n");
      out.write("          from { transform: translateX(-50px); opacity: 0; }\n");
      out.write("          to { transform: translateX(0); opacity: 1; }\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        @keyframes slideInFromRight {\n");
      out.write("          from { transform: translateX(50px); opacity: 0; }\n");
      out.write("          to { transform: translateX(0); opacity: 1; }\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        @keyframes slideInFromBottom {\n");
      out.write("          from { transform: translateY(50px); opacity: 0; }\n");
      out.write("          to { transform: translateY(0); opacity: 1; }\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Apply animations to elements */\n");
      out.write("        .welcome-section {\n");
      out.write("          animation: fadeIn 1s ease-out;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .feature-card:nth-child(1) {\n");
      out.write("          animation: slideInFromLeft 0.5s ease-out 0.2s both;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .feature-card:nth-child(2) {\n");
      out.write("          animation: slideInFromLeft 0.5s ease-out 0.4s both;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .feature-card:nth-child(3) {\n");
      out.write("          animation: slideInFromRight 0.5s ease-out 0.6s both;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .feature-card:nth-child(4) {\n");
      out.write("          animation: slideInFromRight 0.5s ease-out 0.8s both;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .hotel-showcase {\n");
      out.write("          animation: fadeIn 1s ease-out 0.5s both;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .stats-section {\n");
      out.write("          animation: slideInFromBottom 0.5s ease-out 0.7s both;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .testimonials {\n");
      out.write("          animation: fadeIn 1s ease-out 0.9s both;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Form Styles */\n");
      out.write("        .styled-form div {\n");
      out.write("            margin-bottom: 15px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .styled-form label {\n");
      out.write("            display: block;\n");
      out.write("            margin-bottom: 5px;\n");
      out.write("            font-weight: bold;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .styled-form input[type=\"text\"],\n");
      out.write("        .styled-form input[type=\"date\"],\n");
      out.write("        .styled-form input[type=\"number\"],\n");
      out.write("        .styled-form input[type=\"password\"],\n");
      out.write("        .styled-form input[type=\"email\"],\n");
      out.write("        .styled-form select,\n");
      out.write("        .styled-form textarea {\n");
      out.write("            width: calc(100% - 22px); /* Account for padding and border */\n");
      out.write("            padding: 10px;\n");
      out.write("            border: 1px solid #ddd;\n");
      out.write("            border-radius: 4px;\n");
      out.write("            box-sizing: border-box; /* Important for width calculation */\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .styled-form button[type=\"submit\"],\n");
      out.write("        .styled-form button[type=\"reset\"],\n");
      out.write("        .button-link {\n");
      out.write("            background: var(--success-color);\n");
      out.write("            color: white;\n");
      out.write("            border: 0;\n");
      out.write("            padding: 10px 15px;\n");
      out.write("            text-decoration: none;\n");
      out.write("            border-radius: 4px;\n");
      out.write("            cursor: pointer;\n");
      out.write("            font-size: 16px;\n");
      out.write("            margin-right: 10px;\n");
      out.write("            transition: var(--transition);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .styled-form button[type=\"reset\"] {\n");
      out.write("            background: var(--warning-color);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .button-link {\n");
      out.write("             display: inline-block; /* To allow padding and margin */\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .button-link.edit-link {\n");
      out.write("            background: var(--info-color);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .button-link.delete-link, .button-danger {\n");
      out.write("            background: var(--danger-color);\n");
      out.write("            color: white; /* Ensure text is visible */\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .styled-form button:hover,\n");
      out.write("        .button-link:hover {\n");
      out.write("            opacity: 0.9;\n");
      out.write("            transform: translateY(-2px);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Table Styles */\n");
      out.write("        .styled-table {\n");
      out.write("            width: 100%;\n");
      out.write("            border-collapse: collapse;\n");
      out.write("            margin: 25px 0;\n");
      out.write("            font-size: 0.9em;\n");
      out.write("            min-width: 400px;\n");
      out.write("            border-radius: 8px;\n");
      out.write("            overflow: hidden;\n");
      out.write("            box-shadow: var(--box-shadow);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .styled-table thead tr {\n");
      out.write("            background-color: var(--primary-color);\n");
      out.write("            color: #ffffff;\n");
      out.write("            text-align: left;\n");
      out.write("            font-weight: bold;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .styled-table th,\n");
      out.write("        .styled-table td {\n");
      out.write("            padding: 12px 15px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .styled-table tbody tr {\n");
      out.write("            border-bottom: 1px solid #dddddd;\n");
      out.write("            transition: var(--transition);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .styled-table tbody tr:nth-of-type(even) {\n");
      out.write("            background-color: #f3f4f6;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .styled-table tbody tr:hover {\n");
      out.write("            background-color: #f0f4ff;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .styled-table tbody tr:last-of-type {\n");
      out.write("            border-bottom: 2px solid var(--secondary-color);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .styled-table tbody tr.active-row {\n");
      out.write("            font-weight: bold;\n");
      out.write("            color: var(--primary-color);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .action-link {\n");
      out.write("            margin-right: 8px;\n");
      out.write("            padding: 5px 10px;\n");
      out.write("            text-decoration: none;\n");
      out.write("            color: white;\n");
      out.write("            border-radius: 3px;\n");
      out.write("            font-size: 0.9em;\n");
      out.write("            transition: var(--transition);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .action-link:hover {\n");
      out.write("            transform: translateY(-2px);\n");
      out.write("            box-shadow: 0 2px 4px rgba(0,0,0,0.1);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Report Specific Styles */\n");
      out.write("        .report-form {\n");
      out.write("            margin-bottom: 20px;\n");
      out.write("            padding: 20px;\n");
      out.write("            border: 1px solid #eee;\n");
      out.write("            border-radius: 8px;\n");
      out.write("            background-color: #f9fafb;\n");
      out.write("            box-shadow: 0 2px 4px rgba(0,0,0,0.05);\n");
      out.write("            transition: var(--transition);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .report-form:hover {\n");
      out.write("            box-shadow: 0 4px 8px rgba(0,0,0,0.1);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .report-form h3 {\n");
      out.write("            margin-top: 0;\n");
      out.write("            color: var(--primary-color);\n");
      out.write("            font-size: 1.2rem;\n");
      out.write("            border-bottom: 2px solid var(--accent-color);\n");
      out.write("            padding-bottom: 8px;\n");
      out.write("            margin-bottom: 15px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .form-divider {\n");
      out.write("            margin: 30px 0;\n");
      out.write("            border: 0;\n");
      out.write("            height: 1px;\n");
      out.write("            background-image: linear-gradient(to right, rgba(0, 0, 0, 0), rgba(0, 0, 0, 0.1), rgba(0, 0, 0, 0));\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .report-summary {\n");
      out.write("            font-size: 1.1em;\n");
      out.write("            padding: 15px;\n");
      out.write("            background-color: #f0f4ff;\n");
      out.write("            border-left: 5px solid var(--secondary-color);\n");
      out.write("            border-radius: 4px;\n");
      out.write("            margin: 20px 0;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .confirmation-table {\n");
      out.write("            margin-bottom: 20px;\n");
      out.write("            width: 100%;\n");
      out.write("            border-collapse: collapse;\n");
      out.write("            border-radius: 8px;\n");
      out.write("            overflow: hidden;\n");
      out.write("            box-shadow: 0 2px 4px rgba(0,0,0,0.05);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .confirmation-table th {\n");
      out.write("            text-align: right;\n");
      out.write("            padding: 12px 15px;\n");
      out.write("            background-color: #f9fafb;\n");
      out.write("            width: 40%;\n");
      out.write("            font-weight: 600;\n");
      out.write("            color: var(--dark-color);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .confirmation-table td {\n");
      out.write("            text-align: left;\n");
      out.write("            padding: 12px 15px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .confirmation-table tr {\n");
      out.write("            border-bottom: 1px solid #eee;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Error Page Specifics */\n");
      out.write("        .error-details {\n");
      out.write("            background-color: #fff3cd;\n");
      out.write("            border: 1px solid #ffeeba;\n");
      out.write("            padding: 20px;\n");
      out.write("            margin-top: 20px;\n");
      out.write("            border-radius: 8px;\n");
      out.write("            box-shadow: 0 2px 4px rgba(0,0,0,0.05);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .error-details h4 {\n");
      out.write("            margin-top: 0;\n");
      out.write("            color: #856404;\n");
      out.write("            font-size: 1.2rem;\n");
      out.write("            margin-bottom: 15px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .error-details pre {\n");
      out.write("            white-space: pre-wrap;\n");
      out.write("            background: #f8f9fa;\n");
      out.write("            padding: 15px;\n");
      out.write("            border: 1px solid #dee2e6;\n");
      out.write("            border-radius: 4px;\n");
      out.write("            max-height: 300px;\n");
      out.write("            overflow-y: auto;\n");
      out.write("            font-family: monospace;\n");
      out.write("            font-size: 0.9rem;\n");
      out.write("        }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <div class=\"container\">\n");
      out.write("        <header>\n");
      out.write("            <h1>Luxury Hotel Management</h1>\n");
      out.write("            <nav>\n");
      out.write("                <ul>\n");
      out.write("                    <li><a href=\"index.jsp\" class=\"active\"><i class=\"fas fa-home\"></i> Home</a></li>\n");
      out.write("                    <li><a href=\"addReservation\"><i class=\"fas fa-calendar-plus\"></i> Add Reservation</a></li>\n");
      out.write("                    <li><a href=\"displayReservations\"><i class=\"fas fa-list\"></i> View Reservations</a></li>\n");
      out.write("                    <li><a href=\"reports\"><i class=\"fas fa-chart-bar\"></i> Reports</a></li>\n");
      out.write("                </ul>\n");
      out.write("            </nav>\n");
      out.write("        </header>\n");
      out.write("\n");
      out.write("        <main>\n");
      out.write("            <section class=\"welcome-section\">\n");
      out.write("                <h2>Welcome to Luxury Hotel Management System</h2>\n");
      out.write("                <p class=\"welcome-message\">\n");
      out.write("                    Experience the ultimate in hotel management efficiency. Our comprehensive system allows you to manage reservations, \n");
      out.write("                    track room availability, generate reports, and provide exceptional service to your guests.\n");
      out.write("                </p>\n");
      out.write("                \n");
      out.write("                ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("                ");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("                \n");
      out.write("                <div class=\"cta-buttons\">\n");
      out.write("                    <a href=\"addReservation\" class=\"btn btn-primary\"><i class=\"fas fa-calendar-plus\"></i> New Reservation</a>\n");
      out.write("                    <a href=\"displayReservations\" class=\"btn btn-secondary\"><i class=\"fas fa-list\"></i> View All Reservations</a>\n");
      out.write("                </div>\n");
      out.write("            </section>\n");
      out.write("            \n");
      out.write("            <!-- Hotel Image Showcase with Automatic Slideshow -->\n");
      out.write("            <div class=\"hotel-showcase\">\n");
      out.write("                <div class=\"showcase-slide active\"></div>\n");
      out.write("                <div class=\"showcase-slide\"></div>\n");
      out.write("                <div class=\"showcase-slide\"></div>\n");
      out.write("                <div class=\"showcase-caption\">Experience luxury at its finest</div>\n");
      out.write("            </div>\n");
      out.write("            \n");
      out.write("            <!-- Features Section -->\n");
      out.write("            <section class=\"features-grid\">\n");
      out.write("                <div class=\"feature-card\">\n");
      out.write("                    <div class=\"feature-icon\"><i class=\"fas fa-calendar-check\"></i></div>\n");
      out.write("                    <h3>Reservation Management</h3>\n");
      out.write("                    <p>Easily create, update, and cancel reservations with our intuitive interface.</p>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"feature-card\">\n");
      out.write("                    <div class=\"feature-icon\"><i class=\"fas fa-bed\"></i></div>\n");
      out.write("                    <h3>Room Availability</h3>\n");
      out.write("                    <p>Real-time tracking of room availability to maximize occupancy rates.</p>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"feature-card\">\n");
      out.write("                    <div class=\"feature-icon\"><i class=\"fas fa-chart-line\"></i></div>\n");
      out.write("                    <h3>Comprehensive Reports</h3>\n");
      out.write("                    <p>Generate detailed reports on occupancy, revenue, and guest statistics.</p>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"feature-card\">\n");
      out.write("                    <div class=\"feature-icon\"><i class=\"fas fa-concierge-bell\"></i></div>\n");
      out.write("                    <h3>Guest Services</h3>\n");
      out.write("                    <p>Track guest preferences and special requests to enhance their experience.</p>\n");
      out.write("                </div>\n");
      out.write("            </section>\n");
      out.write("            \n");
      out.write("            <!-- Stats Section -->\n");
      out.write("            <section class=\"stats-section\">\n");
      out.write("                <div class=\"stat-item\">\n");
      out.write("                    <span class=\"stat-number\" id=\"roomCount\">120</span>\n");
      out.write("                    <span class=\"stat-label\">Luxury Rooms</span>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"stat-item\">\n");
      out.write("                    <span class=\"stat-number\" id=\"guestCount\">1500+</span>\n");
      out.write("                    <span class=\"stat-label\">Happy Guests</span>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"stat-item\">\n");
      out.write("                    <span class=\"stat-number\" id=\"staffCount\">50</span>\n");
      out.write("                    <span class=\"stat-label\">Staff Members</span>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"stat-item\">\n");
      out.write("                    <span class=\"stat-number\" id=\"ratingCount\">4.9</span>\n");
      out.write("                    <span class=\"stat-label\">Average Rating</span>\n");
      out.write("                </div>\n");
      out.write("            </section>\n");
      out.write("            \n");
      out.write("            <!-- Testimonials Section -->\n");
      out.write("            <section class=\"testimonials\">\n");
      out.write("                <h2>What Our Clients Say</h2>\n");
      out.write("                <div class=\"testimonial-container\">\n");
      out.write("                    <div class=\"testimonial-slide active\">\n");
      out.write("                        <p class=\"testimonial-text\">This hotel management system has revolutionized our operations. We've seen a 30% increase in efficiency since implementation.</p>\n");
      out.write("                        <p class=\"testimonial-author\">John Doe</p>\n");
      out.write("                        <p class=\"testimonial-role\">Hotel Manager, Grand Plaza</p>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"testimonial-slide\">\n");
      out.write("                        <p class=\"testimonial-text\">The reporting features are exceptional. I can now make data-driven decisions that have improved our revenue by 25%.</p>\n");
      out.write("                        <p class=\"testimonial-author\">Jane Smith</p>\n");
      out.write("                        <p class=\"testimonial-role\">Director of Operations, Seaside Resort</p>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"testimonial-slide\">\n");
      out.write("                        <p class=\"testimonial-text\">The intuitive interface made training our staff a breeze. Everyone adapted to the system within days.</p>\n");
      out.write("                        <p class=\"testimonial-author\">Robert Johnson</p>\n");
      out.write("                        <p class=\"testimonial-role\">HR Director, Mountain View Hotel</p>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"testimonial-dots\">\n");
      out.write("                    <span class=\"dot active\" onclick=\"currentTestimonial(0)\"></span>\n");
      out.write("                    <span class=\"dot\" onclick=\"currentTestimonial(1)\"></span>\n");
      out.write("                    <span class=\"dot\" onclick=\"currentTestimonial(2)\"></span>\n");
      out.write("                </div>\n");
      out.write("            </section>\n");
      out.write("        </main>\n");
      out.write("\n");
      out.write("        <footer>\n");
      out.write("            <p>&copy; 2025 Luxury Hotel Management System | Designed for exceptional service</p>\n");
      out.write("        </footer>\n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write("    <!-- JavaScript for interactive elements -->\n");
      out.write("    <script>\n");
      out.write("        // Slideshow functionality for hotel showcase\n");
      out.write("        let currentSlide = 0;\n");
      out.write("        const slides = document.querySelectorAll('.showcase-slide');\n");
      out.write("        \n");
      out.write("        function showSlide(n) {\n");
      out.write("            // Hide all slides\n");
      out.write("            for (let i = 0; i < slides.length; i++) {\n");
      out.write("                slides[i].classList.remove('active');\n");
      out.write("            }\n");
      out.write("            // Show the selected slide\n");
      out.write("            slides[n].classList.add('active');\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        function nextSlide() {\n");
      out.write("            currentSlide = (currentSlide + 1) % slides.length;\n");
      out.write("            showSlide(currentSlide);\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        // Auto-advance slides every 5 seconds\n");
      out.write("        setInterval(nextSlide, 5000);\n");
      out.write("        \n");
      out.write("        // Testimonial slider functionality\n");
      out.write("        let currentTestimonialIndex = 0;\n");
      out.write("        const testimonials = document.querySelectorAll('.testimonial-slide');\n");
      out.write("        const dots = document.querySelectorAll('.dot');\n");
      out.write("        \n");
      out.write("        function currentTestimonial(n) {\n");
      out.write("            showTestimonial(currentTestimonialIndex = n);\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        function showTestimonial(n) {\n");
      out.write("            // Hide all testimonials\n");
      out.write("            for (let i = 0; i < testimonials.length; i++) {\n");
      out.write("                testimonials[i].classList.remove('active');\n");
      out.write("                dots[i].classList.remove('active');\n");
      out.write("            }\n");
      out.write("            // Show the selected testimonial\n");
      out.write("            testimonials[n].classList.add('active');\n");
      out.write("            dots[n].classList.add('active');\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        function nextTestimonial() {\n");
      out.write("            currentTestimonialIndex = (currentTestimonialIndex + 1) % testimonials.length;\n");
      out.write("            showTestimonial(currentTestimonialIndex);\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        // Auto-advance testimonials every 8 seconds\n");
      out.write("        setInterval(nextTestimonial, 8000);\n");
      out.write("        \n");
      out.write("        // Animate stats counting up\n");
      out.write("        function animateStats() {\n");
      out.write("            const stats = document.querySelectorAll('.stat-number');\n");
      out.write("            const targetValues = [120, 1500, 50, 4.9]; // Target values for each stat\n");
      out.write("            const duration = 2000; // Animation duration in milliseconds\n");
      out.write("            const frameDuration = 1000 / 60; // 60fps\n");
      out.write("            const totalFrames = Math.round(duration / frameDuration);\n");
      out.write("            \n");
      out.write("            stats.forEach((stat, index) => {\n");
      out.write("                let frame = 0;\n");
      out.write("                const target = targetValues[index];\n");
      out.write("                const initialValue = 0;\n");
      out.write("                const increment = (target - initialValue) / totalFrames;\n");
      out.write("                \n");
      out.write("                const counter = setInterval(() => {\n");
      out.write("                    frame++;\n");
      out.write("                    const value = initialValue + (increment * frame);\n");
      out.write("                    \n");
      out.write("                    if (index === 3) { // For the rating which is a decimal\n");
      out.write("                        stat.textContent = value.toFixed(1);\n");
      out.write("                    } else {\n");
      out.write("                        stat.textContent = Math.floor(value);\n");
      out.write("                        if (index === 1 && frame === totalFrames) stat.textContent += '+'; // Add + back to 1500+\n");
      out.write("                    }\n");
      out.write("                    \n");
      out.write("                    if (frame === totalFrames) {\n");
      out.write("                        clearInterval(counter);\n");
      out.write("                    }\n");
      out.write("                }, frameDuration);\n");
      out.write("            });\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        // Run animations when page loads\n");
      out.write("        document.addEventListener('DOMContentLoaded', function() {\n");
      out.write("            // Start with first slide\n");
      out.write("            showSlide(0);\n");
      out.write("            \n");
      out.write("            // Start with first testimonial\n");
      out.write("            showTestimonial(0);\n");
      out.write("            \n");
      out.write("            // Animate stats\n");
      out.write("            animateStats();\n");
      out.write("            \n");
      out.write("            // Add smooth scrolling for navigation\n");
      out.write("            document.querySelectorAll('a[href^=\"#\"]').forEach(anchor => {\n");
      out.write("                anchor.addEventListener('click', function (e) {\n");
      out.write("                    e.preventDefault();\n");
      out.write("                    document.querySelector(this.getAttribute('href')).scrollIntoView({\n");
      out.write("                        behavior: 'smooth'\n");
      out.write("                    });\n");
      out.write("                });\n");
      out.write("            });\n");
      out.write("        });\n");
      out.write("    </script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent(null);
    // /index.jsp(850,16) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty successMessage}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\n");
        out.write("                    <p class=\"message success-message\">");
        if (_jspx_meth_c_005fout_005f0(_jspx_th_c_005fif_005f0, _jspx_page_context))
          return true;
        out.write("</p>\n");
        out.write("                ");
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_c_005fout_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fout_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
    // /index.jsp(851,55) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fout_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${successMessage}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
    int _jspx_eval_c_005fout_005f0 = _jspx_th_c_005fout_005f0.doStartTag();
    if (_jspx_th_c_005fout_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f1.setParent(null);
    // /index.jsp(853,16) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty errorMessage}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
    if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\n");
        out.write("                    <p class=\"message error-message\">");
        if (_jspx_meth_c_005fout_005f1(_jspx_th_c_005fif_005f1, _jspx_page_context))
          return true;
        out.write("</p>\n");
        out.write("                ");
        int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f1 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_c_005fout_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fout_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f1);
    // /index.jsp(854,53) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fout_005f1.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${errorMessage}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
    int _jspx_eval_c_005fout_005f1 = _jspx_th_c_005fout_005f1.doStartTag();
    if (_jspx_th_c_005fout_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f1);
    return false;
  }
}
